name: Embed code in README

on:
  push:
    branches:
      - main

jobs:
  embed-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          ref: ${{ github.head_ref }}

      - name: Markdown Embed Code From File - Fork
        uses: technology-studio-forks/markdown-embed-code@v1.1.4
        with:
          markdown: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "auto commit for embedding"
          no_change: "No change on Readme."
          silent: false
